CREATE TABLE order_table (
  id VARCHAR(50) PRIMARY KEY, 
  order_number VARCHAR(10) NOT NULL, -- unique identifier for each order
  supplier_gst VARCHAR(30) NOT NULL, -- gst number of the supplier 
  supplier_name VARCHAR(255), -- name of the supplier entity
  buyer_gst VARCHAR(30) NOT NULL, -- buyer gst number 
  buyer_name VARCHAR(100) NOT NULL, -- name of the buyer
  godown_id VARCHAR(50), -- location id of the godown location
  godown_name VARCHAR(100), -- location name of the godown
  quantity DECIMAL(10, 2) NOT NULL, -- combined quantity for the order
  single_quantity DECIMAL(10, 2) NOT NULL, -- actual quantity of the order 
  product_id VARCHAR(50) NOT NULL, -- unique id of product
  product_name VARCHAR(100) NOT NULL, -- official grade name that was ordered
  delivery_location_id VARCHAR(50),  -- location id of the delivery location
  delivery_location_name VARCHAR(100) , -- location name of the delivery location
  dispatch_date DATE, -- date of dispatch of the order
  due_date DATE, -- due date for the order
  buyer_due_date DATE, -- due date of the order for the buyer
  expected_delivery_date DATE, -- expected date of delivery by our internal calculations
  actual_delivery_date DATE, -- actual date on which order was delivered
  supplier_due_date DATE, -- due date for the supplier for supplier payment
  order_status VARCHAR(50) NOT NULL , -- status of order
  buyer_payment_terms VARCHAR(100), -- payment terms opted by the buyer for paying 
  delivery_address TEXT, -- complete delivery address for the order
  transport_address TEXT, -- address that is shared with the transporter vendor for delivery
  is_eway_bill_created BOOLEAN, -- is eway bill created or no
  buyer_po_number VARCHAR(100), -- buyer po number
  delivery_buyer_payment_terms VARCHAR(255), -- DO NOT USE THIS 
  eway_bill_expiry_date DATE, -- date on which eway bill will get expired 
  delay_score INTEGER DEFAULT 0, -- delay score, no delay means 0 delay days
  logistic_delay_score INTEGER DEFAULT 0, -- logistic delay score can be minimum of -1 
  lr_number VARCHAR(50), -- lr number of the transporter
  driver_mobile_number VARCHAR(20), -- mobile number of person driving
  transporter_name VARCHAR(100), -- name of the transporter vendor company
  freight_cost INTEGER, -- actual freight cost of the order
  last_freight_cost INTEGER, -- freight cost of the last order that placed between the same godown and delivery location
  freight_payment_status VARCHAR(50), -- payment status for the freight
  system_freight_cost INTEGER, -- freight cost generated by system automation logic
  max_possible_freight_cost INTEGER, -- upper threshold for freight cost for system generated cost
  transit_distance_in_km INTEGER, -- transit distance between godown and delivery location
  supplier_credit_note_value DECIMAL(10, 2), -- credit note offered to supplier
  buyer_price DECIMAL(10, 2), -- per kg price of the order confirmed by buyer
  buyer_credit_note_value DECIMAL(10, 2), -- credit note offered to buyer
  invoice_number VARCHAR(50), -- unique identifier for invoices in zoho books
  supplier_price DECIMAL(10, 2),-- per kg price of order confirmed by the supplier
  bill_number VARCHAR(50), -- bill id generated for supplier
  purchase_order_number VARCHAR(50), -- purchase order number for the buyer
  margin DECIMAL(5, 2), -- internal profit margin in the order
  total_amount DECIMAL(10, 2), -- total selling cost of the order for the buyer
  utr_number VARCHAR(50), -- transaction id of payment made by buyer for order
  is_payment_made_to_supplier BOOLEAN, -- is payment made to supplier 
  freight_payment_application_status VARCHAR(100) CHECK (freight_payment_application_status IN ('ACCEPTED', 'REJECTED')),
  freight_bill_status VARCHAR(20) CHECK (freight_bill_status IN ('ACCEPTED', 'REJECTED')),
  freight_pod_status VARCHAR(20) CHECK (freight_pod_status  IN ('ACCEPTED', 'REJECTED')),
  rejection_reason TEXT, -- reason for freight request rejection
  reapply_reason TEXT, -- reason to reapply after freight rejection 
  applied_for_freight_payment_at TIMESTAMP,
  created_at TIMESTAMP, -- order created at time
  updated_at TIMESTAMP, -- order updated at time 
  invoice_status VARCHAR(50)), -- status of invoice , can be paid or unpaid or void
  invoice_value DECIMAL(10, 2), -- total cost on the invoice 
  invoice_due_days INTEGER,  -- DO NOT USE THIS 
  invoice_balance DECIMAL(10, 2), -- Pending amount due against the buyer's invoice
  overdue_amount DECIMAL(10, 2), -- Over due of the buyer invoice -- //TODO:
  adjusted_system_distance INTEGER, -- system distance in kms later adjusted DO NOT USE IT
  tracking_status VARCHAR(100), -- tracking status from cargo exchange 
  pod_reason TEXT,
  bill_reason TEXT,
  lr_reason TEXT,
  pod_remark TEXT,
  bill_remark TEXT,
  lr_remark TEXT,
  lr_status VARCHAR(50), -- status of lr, can be UPLOADED, ACCEPTED, REJECTED, REUPLOADED
  driver_coordinator_name VARCHAR(100), -- driver coordinate name 
  transport_region VARCHAR(50), -- transporter region 
  group_state_owner VARCHAR(100), -- group state owner 
  buyer_account_manager VARCHAR(100), -- buyer account manager 
  supplier_account_manager VARCHAR(100), -- supplier account manager
  is_return BOOLEAN, -- is this is returned order or not
  return_order_created_from VARCHAR(50), -- original order from which this return order is created from 
  buyer_poc VARCHAR(100), -- Phone number Point of contact at buyer side 
  buyer_poc_name VARCHAR(100), -- Name of point of contact at buyer side
  supplier_poc VARCHAR(100), -- Phone number point of contact at supplier side 
  supplier_poc_name VARCHAR(100), -- Name of point of contact at supplier side
  tags text, -- tags concatenated via comma separated string 
  freight_quotes_count INTEGER,
  loading_address TEXT,
  vehicle_number VARCHAR(20),
  delivered_to_with_parent VARCHAR(100), -- concatenated string of the delivery location with its parent location 
  godown_with_parent VARCHAR(100), -- concatenated string of the godown location with its parent location 
  netback DECIMAL(10, 2), -- decimal netback received on every order can be positive or negative 
  buyer_group_id VARCHAR(50), -- group id of the buyer entity group 
  supplier_group_id VARCHAR(50), -- group id of the supplier entity group 
  order_request_id VARCHAR(50), -- order request id from which this order was originally created
  logistic_team_last_edit_by VARCHAR(20), -- email of last person to update the logistic remarks 
  buyer_team_last_edit_by VARCHAR(20), -- email of the last person to update the buyer team remarks
  supplier_team_last_edit_by VARCHAR(20), -- email of the last person to update the supplier team remarks
  general_last_edit_by VARCHAR(20), -- email of last person to update the general remarks
  driver_last_edit_by VARCHAR(20), -- email of last person to edit driver team remarks
  logistic_team_remarks_concatenated TEXT, -- logistic team remarks concatenated with last time it was edited
  buyer_team_remarks_concatenated TEXT, -- buyer team remarks concatenated with last time it was edited
  supplier_team_remarks_concatenated TEXT,-- supplier team remarks concatenated with last time it was edited
  general_remarks_concatenated TEXT,-- general team remarks concatenated with last time it was edited
  driver_remarks_concatenated TEXT,-- driver team remarks concatenated with last time it was edited
  netback_sf DECIMAL(10, 2), -- TODO:
  buyer_delivery_terms VARCHAR(100), -- 
  state_abbreviation CHAR(2),
  load INTEGER,
  freight_offset DECIMAL(10, 2), -- TODO:
  max_dispatch_date DATE,
  min_dispatch_date DATE,
  last_order_days_ago INTEGER,
  group_name VARCHAR(100), --  buyer group name 
  group_limit DECIMAL(10, 2),-- TODO:
  group_blacklisted BOOLEAN, -- is the buyer group blacklisted or not 
  group_business_type VARCHAR(50), -- business type of the buyer group
  group_credit_interest DECIMAL(5, 2), -- interest in percentage offered to each buyer group
  group_credit_limit DECIMAL(10, 2), -- credit limit of the buyer group
  group_credit_tenor VARCHAR(50), -- it usually of formate delivery + X days
  group_markup_value DECIMAL(5, 2), -- TODO:
  group_margin DECIMAL(5, 2), -- margin of money associated with the buyer group
  group_remarks TEXT, -- remarks for the buyer group
  group_unfulfilled_order_count INTEGER, -- orders for buyer group that were unfulfilled in past
  group_waba_price_enabled BOOLEAN, -- weather waba price is enabled or not for buyer group
  highest_gst_slab VARCHAR(50), -- this is range for eg:- 5 Cr. to 25 Cr.
  orders_count INTEGER, -- count of orders for this particular buyer in the past
  account_manager VARCHAR(100), -- account manager of the buyer 
  business_units VARCHAR(255), -- business unit refers to the commodity or Engineering
  group_payment_category VARCHAR(50), -- default payment category of the buyer group
  group_trade_reference_values VARCHAR(255), -- buyer group trade references comma separated
  is_deleted BOOLEAN, -- is the buyer group deleted or not 
  application_type VARCHAR(50), -- application type of the grade ordered in the order
  highest_pan VARCHAR(10), -- PAN number with highest gst limit for buyer
  group_primary_location VARCHAR(100), -- name of the primary location for buyer group
  last_ordered_date DATE, -- date when the last ordered by placed by this group
  coa_required BOOLEAN, -- is COA certificate required or not for the buyer
  last_buyer_app_usage_days_ago INTEGER, -- 
  payment_reminders JSONB, -- TODO: this is always empty or 0
  mobile_app_enabled BOOLEAN, -- mobile app enabled for the buyer or not
  supplier_payment_terms VARCHAR(100), -- payment terms selected by the supplier
  order_priority VARCHAR(20), -- priority of the order
  listings_deactivation_timer INTEGER, -- deactivation timer for the supplier selected for the order
  repeat_reminders_after INTEGER, -- no of hours after which we should send a reminder to the supplier for updating their offers
  special_offer_enabled BOOLEAN, -- is special offer enabled for the supplier of this order
  supplier_orders_count INTEGER, -- no of orders that this supplier has delivered in the past
  group_available_limit DECIMAL(10, 2), -- available limit of money with the buyer group
  sub_application_types VARCHAR(255), -- sub application type of the grade ordered in the order separated by /
  pfp_status VARCHAR(50), -- TODO:
  group_creation_date DATE, -- creation date of the buyer group
  regions VARCHAR(50), -- region from which the buyer group is associated
  group_level_grade_groups TEXT, -- grade groups associated with buyers comma separated
  group_level_tags TEXT, -- buyer group tags comma separated 
  group_hsns TEXT, -- buyer group hsn codes separated by comma
  active_locations TEXT, -- comma separated locations the buyer is active in 
  inactive_locations TEXT, -- comma separated locations that the buyer is inactive in 
  waba_status VARCHAR(50), -- waba status of the buyer for this order
  group_price_receipt VARCHAR(20), -- buyer group price receipt is either active or inactive
  decision_maker_mapped BOOLEAN, -- is the decision maker for the order mapped or not TODO:
  buyer_decision_maker VARCHAR(20), -- phone number of the person who makes decisions for the order from buyer side
  dgft_import DECIMAL(10, 2),-- total count of dgft imports for the buyer
  dgft_import_mapped DECIMAL(10, 2), --  count of dgft imports mapped for the buyer out of total imports
  created_by VARCHAR(100), -- email id of the person who created the order
  last_correspondence_date DATE, -- date of last correspondence TODO:
  last_correspondence_days_ago INTEGER, -- last correspondence days ago
  correspondence_range VARCHAR(255),
  first_note TEXT, -- first note for the buyer 
  second_note TEXT, -- second note for the buyer 
  credit_order DECIMAL(10, 2), -- credit associated with the order TODO:
  lifetime_volume DECIMAL(10, 2), -- lifetime volume of the buyer group associated with this order
  liquidity_buyer_type VARCHAR(50),
  outreach_buyer_type VARCHAR(50),
  days_passed INTEGER,
  days_passed_label VARCHAR(50),
  opportunity TEXT,
  volume_supplied DECIMAL(10, 2),
  supplier_activated BOOLEAN,
  liquidity_type VARCHAR(50),
  liquidity_buyer_type_attrition_slab VARCHAR(50),
  finance_update_count INTEGER,
  email_id_count INTEGER,
  parent_child_available BOOLEAN,
  ceo BOOLEAN,
  coo BOOLEAN,
  dm_owner BOOLEAN,
  dm_purchase_manager BOOLEAN,
  finance BOOLEAN,
  gst VARCHAR(15),
  logistics BOOLEAN,
  md BOOLEAN,
  owner BOOLEAN,
  purchase_head BOOLEAN,
  purchase_manager BOOLEAN,
  sales_manager BOOLEAN,
  undefined_role BOOLEAN,
  tam VARCHAR(100),
  tag_category VARCHAR(50),
  buyer_decision_maker_person VARCHAR(100),
  buyer_decision_maker_email VARCHAR(100),
  ordered_grade_number VARCHAR(50),
  ordered_grade_group VARCHAR(50),
  pan VARCHAR(10),
  total_mapped_qty DECIMAL(10, 2),
  last_6mnt_lowest_not_adjusted DECIMAL(10, 2),
  last_6mnt_lowest_not_adjusted_order_no VARCHAR(50),
  last_6mnt_lowest_adjusted DECIMAL(10, 2),
  last_6mnt_lowest_adjusted_order_no VARCHAR(50),
  warehouse_parent_name VARCHAR(100),
  destination_parent_name VARCHAR(100),
  app_live_price DECIMAL(10, 2),
  l1_supplier_name VARCHAR(100),
  l1_netback DECIMAL(10, 2),
  l2_supplier_name VARCHAR(100),
  l2_netback DECIMAL(10, 2),
  l3_supplier_name VARCHAR(100),
  l3_netback DECIMAL(10, 2),
  freight_quotes_l1 DECIMAL(10, 2),
  freight_quotes_l2 DECIMAL(10, 2),
  freight_quotes_l3 DECIMAL(10, 2),
  change_time TIMESTAMP,
  probable_supplier_group_id VARCHAR(50),
  probable_supplier_group_name VARCHAR(100),
  availability VARCHAR(50),
  buyer_type VARCHAR(50),
  company_gst VARCHAR(15),
  order_created_by VARCHAR(100)
);

CREATE INDEX idx_order_number ON order_table(order_number);
CREATE INDEX idx_supplier_id ON order_table(supplier_id);
CREATE INDEX idx_buyer_id ON order_table(buyer_id);
CREATE INDEX idx_product_id ON order_table(product_id);
CREATE INDEX idx_status ON order_table(status);
CREATE INDEX idx_dispatch_date ON order_table(dispatch_date);
CREATE INDEX idx_due_date ON order_table(due_date);
CREATE INDEX idx_created_at ON order_table(created_at);