# docker-compose.yml
version: '3.8'

services:
  starrocks-fe:
    image: starrocks/fe:latest
    container_name: starrocks-fe
    ports:
      - "8030:8030"  # Web UI
      - "9020:9020"  # RPC port
      - "9030:9030"  # MySQL protocol port
    environment:
      - FE_SERVERS=starrocks-fe:9010
      - PRIORITY_NETWORKS=172.0.0.0/8
    volumes:
      - ./fe/meta:/opt/starrocks/fe/meta
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8030"]
      interval: 30s
      timeout: 10s
      retries: 3

  starrocks-be:
    image: starrocks/be:latest
    container_name: starrocks-be
    ports:
      - "9060:9060"  # BE HTTP port
      - "9050:9050"  # BE heartbeat port
      - "8040:8040"  # BE webserver port
    environment:
      - FE_SERVERS=starrocks-fe:9020
      - PRIORITY_NETWORKS=172.0.0.0/8
    volumes:
      - ./be/storage:/opt/starrocks/be/storage
    depends_on:
      - starrocks-fe
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8040"]
      interval: 30s
      timeout: 10s
      retries: 3